version: '3.7'

services:
  database_provider:
    image: postgres
    container_name: database_provider
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=providers
      - POSTGRES_PASSWORD=prisma
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: api_providers
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - database_provider
    depends_on:
      - database_provider

volumes:
  pgdata:
    driver: local
